export const PRODUCT_LABELS = {
  ERROR_LOADING_PRODUCT: 'Error loading product',
  PRODUCT_NOT_FOUND: 'Product not found',
  ADD_TO_CART: 'ADD TO CART',
  STORAGE: 'STORAGE',
  STORAGE_QUESTION: 'STORAGE. HOW MUCH SPACE DO YOU NEED?',
  COLOR: 'COLOR',
  COLOR_QUESTION: 'COLOR. PICK YOUR FAVOURITE.',
  SPECIFICATIONS: 'SPECIFICATIONS',
  SIMILAR_ITEMS: 'SIMILAR ITEMS',
} as const;